/* Generated By:JavaCC: Do not edit this line. RuleSetParserConstants.java */
package ch.parren.jdepchk.rules.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RuleSetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SHELL_COMMENT = 5;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int Def = 8;
  /** RegularExpression Id. */
  int Rule = 9;
  /** RegularExpression Id. */
  int Scope = 10;
  /** RegularExpression Id. */
  int Lib = 11;
  /** RegularExpression Id. */
  int Comp = 12;
  /** RegularExpression Id. */
  int Contains = 13;
  /** RegularExpression Id. */
  int AppliesTo = 14;
  /** RegularExpression Id. */
  int Allows = 15;
  /** RegularExpression Id. */
  int Extends = 16;
  /** RegularExpression Id. */
  int Uses = 17;
  /** RegularExpression Id. */
  int Except = 18;
  /** RegularExpression Id. */
  int End = 19;
  /** RegularExpression Id. */
  int This = 20;
  /** RegularExpression Id. */
  int Not = 21;
  /** RegularExpression Id. */
  int Intro = 22;
  /** RegularExpression Id. */
  int Bullet = 23;
  /** RegularExpression Id. */
  int Id = 24;
  /** RegularExpression Id. */
  int RegExp = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SHELL_COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"def\"",
    "\"rule\"",
    "\"scope\"",
    "\"lib\"",
    "\"comp\"",
    "\"contains\"",
    "\"applies-to\"",
    "\"allows\"",
    "\"extends\"",
    "\"uses\"",
    "\"except\"",
    "\"end\"",
    "\"this\"",
    "\"!\"",
    "\":\"",
    "\"-\"",
    "<Id>",
    "<RegExp>",
    "\"=\"",
  };

}
